kind: Deployment
apiVersion: apps/v1
metadata:
  name: chat-app-frontend
  labels:
    app: chat-app
  namespace: chat-app

spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-app-frontend
  template:
    metadata:
      labels:
        app: chat-app-frontend
    spec:
      containers:
        - name: chat-app-container
          image: dockerdev7nsh/chatapp-frontend
          
          ports:
            - containerPort: 80